### ISSUE TITLE
Custom Horizon commands

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#337]
We should allow creating custom commands that map to parameterized reql queries.

There would be two parts:
1. The config to add a custom command
2. Adding the method to the horizon object so it can be used

The server and client would need to be changed

Example config:

``` toml
[commands]
name = "countLabels"
params = [ "x", "y" ]
reql = "r.table('foo').getAll([ x, y ], { index: 'x_and_y_compound' }).count()"
```

On the frontend, you may use it like:

``` js
horizon.countLabels({x: 12, y: 13}).fetch()
```

If you use fetch, it would run the query directly. If you use watch() it will append `.changes()` to the query and then run it. The query would simply fail if it doesn't support changes.

This would add easy extensibility, where instead of going from easy Horizon straight to roll your own backend, you can go to RPC reql queries as a nicer intermediate step.
