### ISSUE TITLE
Using stand alone horizon server and config.toml

### ISSUE THREAD

**Issue by vizo** [rethinkdb/horizon#414]
When i am using stand alone horizon server i get error:

```
Error: No token_secret set! Try setting it in .hz/config.toml or passing it to the Server constructor.
```

but dir .hz is in my root of project, so in same dir as node_modules. config.toml was generated by cli init.

Any idea?
- Server version 1.0.1
- Client version 1.0.1

**Comment by flipace** [comment]
Hi, how are you starting the server/what's the code?

**Comment by vizo** [comment]
const horizon = require('@horizon/server');

const horizonServer = horizon(httpServer);

**Comment by flipace** [comment]
You'll have to pass an options object like so:

``` Javascript
horizon(httpServer, {
    auth: { token_secret: 'insertYourSuperSecretTokenMcSecretHere' }
});
```

I'd also suggest to add `permissions: false` for now until the permissions are fully implemented to be used with the standalone variant too.

If you use the standalone server, there's no need to have the .hz folder around in your application. (except for the case in which you'd like to try out permissions already)

edited: fixed incorrect opts object

**Comment by vizo** [comment]
I want to try it ;) Is there other way to use .hz?

**Comment by flipace** [comment]
If you want to try it you'll have to make sure that the config toml files configuration matches the server configuration (e.g. if you use a manually started rehtinkdb instance point it to the correct port/host), create a file `new_schema.toml` (as an example) like this:

``` toml
[collections.projects]
indexes = [
  "owner"
]

[groups.default.rules.read]
template = "collection('projects').anyRead()"

[groups.default.rules.store_message]
template = "collection('messages').store()"
validator = """
  (context, oldValue, newValue) => {
    return typeof newValue.name === 'string';
  }
"""
```

And then run `hz set-schema new_schema.toml`. This should insert the necessary fields in the database and "all users" should be able to "read" and "store" anything (storing allows only for docs where name is a string).
