### ISSUE TITLE
Remove and removeAll permissions broken

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#552]
According to a user in slack, the following permission doesn't work:

``` toml
[groups.authenticated.rules.remove_own_messages]
template = "collection('todos').removeAll({owner: userId()})"
```

He also mentioned permissions for `remove` not working until a validator function was also added.
