### ISSUE TITLE
Gracefully handle parse errors in config.toml

### ISSUE THREAD

**Issue by doefler** [rethinkdb/horizon#756]
Hi I just did npm install -g horizon@2.0.0-beta-5
Now I am trying to run hz migrate which is not working for me.
I am running the command from the my project folder.

I have tried a lot of variations which haven't worked for me. Can you point out what I am doing wrong:

hz migrate
hz migrate myhorizonapp
hz migrate --project-name myhorizonapp
hz migrate -n myhorizonapp
hz migrate -n "myhorizonapp"
hz migrate "myhorizonapp"
hz migrate ./
hz migrate .hz/config.toml
hz migrate .hz/
hz migrate .

Errors I got:

/Users/username/.nvm/versions/node/v4.2.1/lib/node_modules/horizon/src/migrate.js:119
throw new Error('No project_name given');
^

/Users/username/.nvm/versions/node/v4.2.1/lib/node_modules/horizon/node_modules/toml/lib/parser.js:3946
throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
^
SyntaxError: Expected "#", "E", "\n", "\r", "_", "e", [ \t] or [0-9] but "." found.
Thank you.

**Comment by danielmewes** [comment]
Pinging @deontologician

**Comment by deontologician** [comment]
@doefler Could you go into the project directory, do `hz migrate` and paste the output? That's likely all you need to do if you already have `project_name` set in your config

**Comment by doefler** [comment]
Hi @deontologician 
Thank you for looking into this 😄 

The output from running `hz migrate` in the project directory is:

``` zsh
/Users/username/.nvm/versions/node/v4.2.1/lib/node_modules/horizon/node_modules/toml/lib/parser.js:3946
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
      ^
SyntaxError: Expected "#", "E", "\n", "\r", "_", "e", [ \t] or [0-9] but "." found.
```

**Comment by deontologician** [comment]
Would you mind pasting your config.toml here? It looks like a syntax error when parsing it (though we should be catching the error and failing more gracefully). (I should mention you should be sure to delete any secret tokens from the config before pasting, we've moved secrets out to `secrets.toml` in 2.0 for this reason)

**Comment by doefler** [comment]
Here you go @deontologician 

``` toml
# This is a TOML file

###############################################################################
# IP options
# 'bind' controls which local interfaces will be listened on
# 'port' controls which port will be listened on
#------------------------------------------------------------------------------
bind = 0.0.0.0
# port = 8181


###############################################################################
# HTTPS Options
# 'secure' will disable HTTPS and use HTTP instead when set to 'false'
# 'key_file' and 'cert_file' are required for serving HTTPS
#------------------------------------------------------------------------------
# secure = true
key_file = "horizon-key.pem"
cert_file = "horizon-cert.pem"


###############################################################################
# App Options
# 'project_name' sets the name of the RethinkDB database used to store the
#                application state
# 'serve_static' will serve files from the given directory over HTTP/HTTPS
#------------------------------------------------------------------------------
project_name = "myhorizonapp"
# serve_static = "dist"


###############################################################################
# Data Options
# WARNING: these should probably not be enabled on a publically accessible
# service.  Tables and indexes are not lightweight objects, and allowing them
# to be created like this could open the service up to denial-of-service
# attacks.
# 'auto_create_collection' creates a collection when one is needed but does not exist
# 'auto_create_index' creates an index when one is needed but does not exist
#------------------------------------------------------------------------------
# auto_create_collection = false
# auto_create_index = false


###############################################################################
# RethinkDB Options
# 'connect' and 'start_rethinkdb' are mutually exclusive
# 'connect' will connect to an existing RethinkDB instance
# 'start_rethinkdb' will run an internal RethinkDB instance
# 'rdb_timeout' is the number of seconds to wait when connecting to RethinkDB
#------------------------------------------------------------------------------
# connect = "localhost:28015"
# start_rethinkdb = false
# rdb_timeout = 30


###############################################################################
# Debug Options
# 'debug' enables debug log statements
#------------------------------------------------------------------------------
# debug = false


###############################################################################
# Authentication Options
# Each auth subsection will add an endpoint for authenticating through the
# specified provider.
# 'token_secret' is the key used to sign jwts
# 'allow_anonymous' issues new accounts to users without an auth provider
# 'allow_unauthenticated' allows connections that are not tied to a user id
# 'auth_redirect' specifies where users will be redirected to after login
# 'access_control_allow_origin' sets a host that can access auth settings
#   (typically your frontend host)
#------------------------------------------------------------------------------
# allow_anonymous = false
# allow_unauthenticated = false
# auth_redirect = "/"
# access_control_allow_origin = ""
#
```
