### ISSUE TITLE
Using "rethinkdb" as an alias for the hz serve CLI connect options would failed

### ISSUE THREAD

**Issue by rguillome** [rethinkdb/horizon#881]
Server version: 2.0.0

I tried to run a dev environment from the current docker-compose.yml and get the following error when the horizon server started : 
```shell
error: Connection to RethinkDB terminated: ReqlDriverError: Could not connect to 28015:28015.
connect EINVAL 0.0.109.111:28015 - Local (0.0.0.0:0)
```

After several tests, i figure it out and It seems that the CLI hz replace the word __rethinkdb__ by and empty String when using it with the `--connect` option.

I fixed it by replacing the alias of the rethinkdb container : __rethinkdb__ by __rethindbtest__ .
The current working docker-compose.yml 
```yaml
  rethinkdbtest:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "8080:8080"
  horizon:
    image: rethinkdb/horizon
    command: su -s /bin/sh horizon -c "hz serve --dev --connect rethinkdbtest:28015 --bind all /usr/app"
    volumes:
      - /home/rguillome/Documents/perso/study/horizon/cv-backend:/usr/app
    links:
      - rethinkdbtest
    ports:
      - "8181:8181"

```
